server:
 port: 8090
mybatis:
  mapper-locations: classpath:xml/*Mapper.xml

vipcoder:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    maximumPoolSize: 10
    defaultTarget: w_0
    testOnBorrow: true
    initialSize: 1
    validationQuery: select 1
     #写库方法前缀
    writePrefix: insert*,update*,delete*
    targets:
      w_0:
        url: jdbc:sqlserver://XXX.XXX.XXX.XXX:1433; DatabaseName=BI_Canal
        username: XXX
        password: XXX
        master: true
      r_0:
        url: jdbc:sqlserver://XXX.XXX.XXX.XXX:1433; DatabaseName=BI_Canal
        username: XXX
        password: XXX